### PR TITLE
Add editor support for .vscode

### PR DESCRIPTION
**Pull request by Rycia**
Add support for VSCode editor settings, including:

1. Formatter
2. Updated WoW API access and error checking
3. .tga file viewing
4. Standardized spacing settings
5. GitHub VSCode tools.

..And a .gitignore configured for VS code automatically by GitHub.

Overall, this push standardizes the formatter and visual studio code setup for anybody editing the project inside of visual studio code, and helps prevents contributors from having completely different formatting styles going forth, alongside some quality-of-life tools for WoW addon development and GitHub itself.

### CODE REVIEW

**Comment by Nevcairiel** [comment]
Routes doesn't actually use space indents, its on tabs, so merging the editorconfig as-is will cause it to be less consistent.

**Comment by Rycia** [comment]
I'll remove .editorconfig then. This is just typically the formatting rules I use for my own repos. If you have any changes you wish to make on this, please do so.

**Comment by Nevcairiel** [comment]
Well I would've suggested to just change editorconfig to indicate tabs, as keeping consistent is usually a good idea. But I also have a editorconfig at the root of my addon workspace to apply to those that don't have a specific one.

**Comment by Rycia** [comment]
..Additionally, for some reason, my other push for adding github issue templates for feature requests and issues got bundled in with this. I'll delete those files for this push and make that one separately.

Please merge when you're good with this.

If you want, go ahead and add your .editorconfig instead so that I can make sure it's the same if you're already using one.

**Comment by Nevcairiel** [comment]
To avoid commits getting all mashed up into the same PR, you can create a dedicated branch for each PR.

**Pull request merged**
